#pragma once
#include <Windows.h>

// Updated offsets from https://imtheo.lol/Offsets/Offsets.hpp (Roblox version-390ba09e7e944154)
// and https://imtheo.lol/Offsets/FFlags.hpp as of 26/04/2026

namespace offs {
    // Core / DataModel
    inline constexpr uintptr_t EnableLoadModule = 0x751fe08;  // (unchanged / still valid)
    inline constexpr uintptr_t loadModule = EnableLoadModule;
    inline constexpr uintptr_t fakeDataModelPtr = 0x7b991d8;           // FakeDataModel::Pointer
    inline constexpr uintptr_t fakeDataModelToDataModel = 0x1d0;       // FakeDataModel::RealDataModel
    inline constexpr uintptr_t children = 0x78;                        // Instance::ChildrenStart
    inline constexpr uintptr_t childrenEnd = 0x8;                      // Instance::ChildrenEnd
    inline constexpr uintptr_t name = 0xb0;                            // Instance::Name
    inline constexpr uintptr_t value = 0xd0;                           // Misc::Value
    inline constexpr uintptr_t classDesc = 0x18;                       // Instance::ClassDescriptor
    inline constexpr uintptr_t classDescToName = 0x8;                  // Instance::ClassName

    // Scripts
    inline constexpr uintptr_t lscriptBc = 0x0;                        // LocalScript::ByteCode
    inline constexpr uintptr_t mscriptBc = 0x0;                        // ModuleScript::ByteCode
    inline constexpr uintptr_t LocalScriptBytecodePointer = 0x10;      // ByteCode::Pointer (if needed)
    inline constexpr uintptr_t ModuleScriptBytecodePointer = 0x10;     // ByteCode::Pointer

    // Common properties
    inline constexpr uintptr_t Adornee = 0x108;                        // Misc::Adornee (updated)
    inline constexpr uintptr_t Anchored = 0x2;                         // PrimitiveFlags::Anchored
    inline constexpr uintptr_t AnimationId = 0xd0;                     // Misc::AnimationId
    inline constexpr uintptr_t AttributeToNext = 0x58;                 // Instance::AttributeToNext
    inline constexpr uintptr_t AttributeToValue = 0x18;                // Instance::AttributeToValue
    inline constexpr uintptr_t AutoJumpEnabled = 0x1d8;                // Humanoid::AutoJumpEnabled (updated)
    inline constexpr uintptr_t BanningEnabled = 0x14C;                 // (keep if still used; no direct match)
    inline constexpr uintptr_t BeamBrightness = 0x190;                 // Beam::Brightness
    inline constexpr uintptr_t BeamColor = 0x120;                      // (Beam color is usually part of Attachment or separate)
    inline constexpr uintptr_t BeamLightEmission = 0x19c;              // Beam::LightEmission
    inline constexpr uintptr_t BeamLightInfuence = 0x1a0;              // Beam::LightInfluence
    inline constexpr uintptr_t CFrame = 0xc0;                          // Primitive::Rotation + Position (or use CFrame directly where available)
    inline constexpr uintptr_t Camera = 0x490;                         // Workspace::CurrentCamera
    inline constexpr uintptr_t CameraMaxZoomDistance = 0x320;          // Player::MaxZoomDistance
    inline constexpr uintptr_t CameraMinZoomDistance = 0x324;          // Player::MinZoomDistance
    inline constexpr uintptr_t CameraMode = 0x328;                     // Player::CameraMode
    inline constexpr uintptr_t CameraPos = 0x11c;                      // Camera::Position
    inline constexpr uintptr_t CameraRotation = 0xf8;                  // Camera::Rotation
    inline constexpr uintptr_t CameraSubject = 0xe8;                   // Camera::CameraSubject
    inline constexpr uintptr_t CameraType = 0x158;                     // Camera::CameraType
    inline constexpr uintptr_t CanCollide = 0x8;                       // PrimitiveFlags::CanCollide
    inline constexpr uintptr_t CanCollideMask = 0x8;
    inline constexpr uintptr_t CanTouch = 0x10;                        // PrimitiveFlags::CanTouch
    inline constexpr uintptr_t CanTouchMask = 0x10;
    inline constexpr uintptr_t CharacterAppearanceId = 0x2C8;          // (still valid)
    inline constexpr uintptr_t ClickDetectorMaxActivationDistance = 0x100; // ClickDetector::MaxActivationDistance
    inline constexpr uintptr_t ClockTime = 0x1b8;                      // Lighting::ClockTime
    inline constexpr uintptr_t CreatorId = 0x188;                      // DataModel::CreatorId
    inline constexpr uintptr_t DataModelDeleterPointer = 0x7A1D390;    // (keep if still used)
    inline constexpr uintptr_t DataModelPrimitiveCount = 0x440;        // DataModel::PrimitiveCount
    inline constexpr uintptr_t DataModelToRenderView1 = 0x1d0;         // DataModel::ToRenderView1
    inline constexpr uintptr_t DataModelToRenderView2 = 0x8;
    inline constexpr uintptr_t DataModelToRenderView3 = 0x28;
    inline constexpr uintptr_t DecalTexture = 0x198;                   // Textures::Decal_Texture
    inline constexpr uintptr_t Dimensions = 0xa60;                     // VisualEngine::Dimensions
    inline constexpr uintptr_t DisplayName = 0x130;                    // Player::DisplayName
    inline constexpr uintptr_t EvaluateStateMachine = 0x1dc;           // Humanoid::EvaluateStateMachine
    inline constexpr uintptr_t FFlagList = 0x782d5f8;                  // FFlagList::Pointer (updated)
    inline constexpr uintptr_t FFlagToValueGetSet = 0x30;              // FFlagList::ToFlag
    inline constexpr uintptr_t FOV = 0x160;                            // Camera::FieldOfView
    inline constexpr uintptr_t FogColor = 0xfc;                        // Lighting::FogColor
    inline constexpr uintptr_t FogEnd = 0x134;                         // Lighting::FogEnd
    inline constexpr uintptr_t FogStart = 0x138;                       // Lighting::FogStart
    inline constexpr uintptr_t ForceNewAFKDuration = 0x1B8;            // (keep)
    inline constexpr uintptr_t FramePositionOffsetX = 0x51C;           // GuiObject position fields
    inline constexpr uintptr_t FramePositionOffsetY = 0x524;
    inline constexpr uintptr_t FramePositionX = 0x518;                 // GuiObject::Position
    inline constexpr uintptr_t FramePositionY = 0x520;
    inline constexpr uintptr_t FrameRotation = 0x188;                  // GuiObject::Rotation
    inline constexpr uintptr_t FrameSizeOffsetX = 0x540;
    inline constexpr uintptr_t FrameSizeOffsetY = 0x544;
    inline constexpr uintptr_t FrameSizeX = 0x538;                     // GuiObject::Size
    inline constexpr uintptr_t FrameSizeY = 0x53C;
    inline constexpr uintptr_t FrameVisible = 0x5B5;                   // GuiObject::Visible
    inline constexpr uintptr_t GameId = 0x190;                         // DataModel::GameId
    inline constexpr uintptr_t GameLoaded = 0x5f8;                     // DataModel::GameLoaded
    inline constexpr uintptr_t Gravity = 0x1d8;                        // World::Gravity
    inline constexpr uintptr_t Health = 0x194;                         // Humanoid::Health
    inline constexpr uintptr_t HealthDisplayDistance = 0x198;          // Humanoid::HealthDisplayDistance (updated)
    inline constexpr uintptr_t HipHeight = 0x1a0;                      // Humanoid::HipHeight
    inline constexpr uintptr_t HumanoidDisplayName = 0xd0;             // Humanoid::DisplayName
    inline constexpr uintptr_t HumanoidState = 0x898;                  // Humanoid::HumanoidState
    inline constexpr uintptr_t HumanoidStateId = 0x20;                 // Humanoid::HumanoidStateID
    inline constexpr uintptr_t InputObject = 0x100;                    // MouseService::InputObject
    inline constexpr uintptr_t InsetMaxX = 0x100;                      // (Gui related)
    inline constexpr uintptr_t InsetMaxY = 0x104;
    inline constexpr uintptr_t InsetMinX = 0xf8;
    inline constexpr uintptr_t InsetMinY = 0xfc;
    inline constexpr uintptr_t InstanceAttributePointer1 = 0x48;       // Instance::AttributeContainer
    inline constexpr uintptr_t InstanceAttributePointer2 = 0x18;       // Instance::AttributeList
    inline constexpr uintptr_t InstanceCapabilities = 0x208;           // (keep)
    inline constexpr uintptr_t JobEnd = 0xd0;                          // TaskScheduler::JobEnd
    inline constexpr uintptr_t JobId = 0x138;                          // DataModel::JobId
    inline constexpr uintptr_t JobStart = 0xc8;                        // TaskScheduler::JobStart
    inline constexpr uintptr_t Job_Name = 0x18;                        // TaskScheduler::JobName
    inline constexpr uintptr_t JobsPointer = 0x0;                      // (TaskScheduler jobs list)
    inline constexpr uintptr_t JumpPower = 0x1b0;                      // Humanoid::JumpPower
    inline constexpr uintptr_t LocalPlayer = 0x130;                    // Player::LocalPlayer
    inline constexpr uintptr_t LocalScriptHash = 0x1b8;                // LocalScript::Hash
    inline constexpr uintptr_t MaterialType = 0x0;                     // Primitive::Material (offset inside Primitive)
    inline constexpr uintptr_t MaxHealth = 0x1b4;                      // Humanoid::MaxHealth
    inline constexpr uintptr_t MaxSlopeAngle = 0x1b8;                  // Humanoid::MaxSlopeAngle
    inline constexpr uintptr_t MeshPartColor3 = 0x194;                 // BasePart::Color3
    inline constexpr uintptr_t MeshPartTexture = 0x328;                // MeshPart::Texture (updated)
    inline constexpr uintptr_t ModelInstance = 0x398;                  // Player::ModelInstance
    inline constexpr uintptr_t ModuleScriptHash = 0x160;               // ModuleScript::Hash
    inline constexpr uintptr_t MoonTextureId = 0xe0;                   // Sky::MoonTextureId
    inline constexpr uintptr_t MousePosition = 0xec;                   // MouseService::MousePosition
    inline constexpr uintptr_t MouseSensitivity = 0x7c388d0;           // MouseService::SensitivityPointer (updated)
    inline constexpr uintptr_t MoveDirection = 0x158;                  // Humanoid::MoveDirection
    inline constexpr uintptr_t NameDisplayDistance = 0x358;            // Player::NameDisplayDistance (or Humanoid::NameDisplayDistance)
    inline constexpr uintptr_t NameSize = 0x10;                        // (string length helper)
    inline constexpr uintptr_t OnDemandInstance = 0x40;                // (keep)
    inline constexpr uintptr_t OutdoorAmbient = 0x108;                 // Lighting::OutdoorAmbient
    inline constexpr uintptr_t Parent = 0x70;                          // Instance::Parent
    inline constexpr uintptr_t PartSize = 0x1b0;                       // Primitive::Size
    inline constexpr uintptr_t Ping = 0xCC;                            // (keep)
    inline constexpr uintptr_t PlaceId = 0x198;                        // DataModel::PlaceId
    inline constexpr uintptr_t PlayerConfigurerPointer = 0x7b6e7e8;    // PlayerConfigurer::Pointer (updated)
    inline constexpr uintptr_t PlayerMouse = 0x1158;                   // Player::Mouse (updated)
    inline constexpr uintptr_t Position = 0xe4;                        // Primitive::Position
    inline constexpr uintptr_t Primitive = 0x148;                      // BasePart::Primitive
    inline constexpr uintptr_t PrimitiveValidateValue = 0x6;           // Primitive::Validate
    inline constexpr uintptr_t PrimitivesPointer1 = 0x3E0;             // (World::Primitives related)
    inline constexpr uintptr_t PrimitivesPointer2 = 0x248;             // World::Primitives (updated path)
    inline constexpr uintptr_t ProximityPromptActionText = 0xd0;       // ProximityPrompt::ActionText
    inline constexpr uintptr_t ProximityPromptEnabled = 0x156;         // ProximityPrompt::Enabled
    inline constexpr uintptr_t ProximityPromptGamepadKeyCode = 0x13c;  // ProximityPrompt::GamepadKeyCode
    inline constexpr uintptr_t ProximityPromptHoldDuraction = 0x140;   // ProximityPrompt::HoldDuration
    inline constexpr uintptr_t ProximityPromptMaxActivationDistance = 0x148; // ProximityPrompt::MaxActivationDistance
    inline constexpr uintptr_t ProximityPromptMaxObjectText = 0xf0;    // ProximityPrompt::ObjectText
    inline constexpr uintptr_t ReadOnlyGravity = 0x9c0;                // Workspace::ReadOnlyGravity (updated)
    inline constexpr uintptr_t RenderJobToDataModel = 0x1c0;           // RenderJob::RealDataModel (updated)
    inline constexpr uintptr_t RenderJobToFakeDataModel = 0x38;        // RenderJob::FakeDataModel
    inline constexpr uintptr_t RenderJobToRenderView = 0x1d0;          // RenderJob::RenderView
    inline constexpr uintptr_t RequireBypass = 0x0;                    // ScriptContext::RequireBypass
    inline constexpr uintptr_t RigType = 0x1c8;                        // Humanoid::RigType
    inline constexpr uintptr_t RootPartR15 = 0x478;                    // Humanoid::HumanoidRootPart
    inline constexpr uintptr_t RootPartR6 = 0x478;
    inline constexpr uintptr_t Rotation = 0xc0;                        // Primitive::Rotation
    inline constexpr uintptr_t RunContext = 0x148;                     // (keep)
    inline constexpr uintptr_t Sandboxed = 0xc5;                       // (keep)
    inline constexpr uintptr_t ScreenGuiEnabled = 0x4cc;               // GuiObject::ScreenGui_Enabled
    inline constexpr uintptr_t ScriptContext = 0x3f0;                  // DataModel::ScriptContext
    inline constexpr uintptr_t Sit = 0x1e0;                            // Humanoid::Sit
    inline constexpr uintptr_t SkyboxBk = 0x110;                       // Sky::SkyboxBk
    inline constexpr uintptr_t SkyboxDn = 0x140;
    inline constexpr uintptr_t SkyboxFt = 0x170;
    inline constexpr uintptr_t SkyboxLf = 0x1a0;
    inline constexpr uintptr_t SkyboxRt = 0x1d0;
    inline constexpr uintptr_t SkyboxUp = 0x200;
    inline constexpr uintptr_t SoundId = 0xe0;                         // Sound::SoundId
    inline constexpr uintptr_t StarCount = 0x260;                      // Sky::StarCount
    inline constexpr uintptr_t StringLength = 0x10;                    // Misc::StringLength
    inline constexpr uintptr_t SunTextureId = 0x230;                   // Sky::SunTextureId
    inline constexpr uintptr_t TagList = 0x0;                          // (keep)
    inline constexpr uintptr_t TaskSchedulerMaxFPS = 0xb0;             // TaskScheduler::MaxFPS
    inline constexpr uintptr_t TaskSchedulerPointer = 0x7c73e50;       // TaskScheduler::Pointer (updated)
    inline constexpr uintptr_t Team = 0x2a0;                           // Player::Team
    inline constexpr uintptr_t TeamColor = 0x364;                      // Player::TeamColor (updated)
    inline constexpr uintptr_t TextLabelText = 0xdc0;                  // GuiObject::Text (updated)
    inline constexpr uintptr_t TextLabelVisible = 0x5b5;               // GuiObject::Visible
    inline constexpr uintptr_t Tool_Grip_Position = 0x494;             // Tool::Grip (approx)
    inline constexpr uintptr_t Transparency = 0xf0;                    // BasePart::Transparency
    inline constexpr uintptr_t UserId = 0x2c8;                         // Player::UserId
    inline constexpr uintptr_t ValueGetSetToValue = 0xc0;              // FFlagList::ToValue
    inline constexpr uintptr_t Velocity = 0xf0;                        // Primitive::AssemblyLinearVelocity
    inline constexpr uintptr_t ViewportSize = 0x2e8;                   // Camera::ViewportSize
    inline constexpr uintptr_t VisualEngine = 0x10;                    // RenderView::VisualEngine
    inline constexpr uintptr_t VisualEnginePointer = 0x7746260;        // VisualEngine::Pointer (updated)
    inline constexpr uintptr_t VisualEngineToDataModel1 = 0xa40;       // VisualEngine::FakeDataModel
    inline constexpr uintptr_t VisualEngineToDataModel2 = 0x1c0;       // (RenderJob path)
    inline constexpr uintptr_t WalkSpeed = 0x1d4;                      // Humanoid::Walkspeed
    inline constexpr uintptr_t WalkSpeedCheck = 0x3bc;                 // Humanoid::WalkspeedCheck
    inline constexpr uintptr_t Workspace = 0x178;                      // DataModel::Workspace
    inline constexpr uintptr_t WorkspaceToWorld = 0x408;               // Workspace::World (updated)
    inline constexpr uintptr_t viewmatrix = 0x130;                     // VisualEngine::ViewMatrix
}
