#pragma once
#include <Windows.h>
// Mirrors `Offsets.hpp` / `FFlags.hpp` (version-acc4b74f79e743b9 / FFlags: version-390ba09e7e944154) for symbols used by SelpExt.
namespace offs {
    inline constexpr uintptr_t EnableLoadModule = 0x751fe08;
    inline constexpr uintptr_t loadModule = EnableLoadModule;
    inline constexpr uintptr_t fakeDataModelPtr = 0x7c1a148;           // updated (FakeDataModel::Pointer)
    inline constexpr uintptr_t fakeDataModelToDataModel = 0x1d0;       // updated (FakeDataModel::RealDataModel)
    inline constexpr uintptr_t children = 0x78;                        // unchanged (Instance::ChildrenStart)
    inline constexpr uintptr_t childrenEnd = 0x8;                      // unchanged (Instance::ChildrenEnd)
    inline constexpr uintptr_t name = 0xb0;                            // unchanged (Instance::Name)
    inline constexpr uintptr_t value = 0xd0;                           // unchanged (Misc::Value)
    inline constexpr uintptr_t classDesc = 0x18;                       // unchanged (Instance::ClassDescriptor)
    inline constexpr uintptr_t classDescToName = 0x8;                  // unchanged (Instance::ClassName)
    inline constexpr uintptr_t lscriptBc = 0x1a8;                      // unchanged
    inline constexpr uintptr_t mscriptBc = 0x150;                      // unchanged
    inline constexpr uintptr_t Adornee = 0x108;                        // updated (Misc::Adornee)
    inline constexpr uintptr_t Anchored = 0x1AE;                       // unchanged (Primitive::Flags)
    inline constexpr uintptr_t AnchoredMask = 0x2;                     // unchanged (PrimitiveFlags::Anchored)
    inline constexpr uintptr_t AnimationId = 0xD0;                     // unchanged (Misc::AnimationId)
    inline constexpr uintptr_t AttributeToNext = 0x58;                 // unchanged (Instance::AttributeToNext)
    inline constexpr uintptr_t AttributeToValue = 0x18;                // unchanged (Instance::AttributeToValue)
    inline constexpr uintptr_t AutoJumpEnabled = 0x1E0;                // updated (Humanoid::AutoJumpEnabled)
    inline constexpr uintptr_t BanningEnabled = 0x14C;
    inline constexpr uintptr_t BeamBrightness = 0x190;                 // unchanged (Beam::Brightness)
    inline constexpr uintptr_t BeamColor = 0x120;
    inline constexpr uintptr_t BeamLightEmission = 0x19C;              // unchanged (Beam::LightEmission)
    inline constexpr uintptr_t BeamLightInfuence = 0x1A0;             // unchanged (Beam::LightInfluence)
    inline constexpr uintptr_t CFrame = 0xC0;                          // unchanged (Primitive::Rotation)
    inline constexpr uintptr_t Camera = 0x490;                         // updated (Workspace::CurrentCamera)
    inline constexpr uintptr_t CameraMaxZoomDistance = 0x320;          // unchanged (Player::MaxZoomDistance)
    inline constexpr uintptr_t CameraMinZoomDistance = 0x324;          // unchanged (Player::MinZoomDistance)
    inline constexpr uintptr_t CameraMode = 0x328;                     // unchanged (Player::CameraMode)
    inline constexpr uintptr_t CameraPos = 0x11C;                      // unchanged (Camera::Position)
    inline constexpr uintptr_t CameraRotation = 0xF8;                  // unchanged (Camera::Rotation)
    inline constexpr uintptr_t CameraSubject = 0xE8;                   // unchanged (Camera::CameraSubject)
    inline constexpr uintptr_t CameraType = 0x158;                     // unchanged (Camera::CameraType)
    inline constexpr uintptr_t CanCollide = 0x1AE;                     // unchanged (Primitive::Flags)
    inline constexpr uintptr_t CanCollideMask = 0x8;                   // unchanged (PrimitiveFlags::CanCollide)
    inline constexpr uintptr_t CanTouch = 0x1AE;                       // unchanged (Primitive::Flags)
    inline constexpr uintptr_t CanTouchMask = 0x10;                    // unchanged (PrimitiveFlags::CanTouch)
    inline constexpr uintptr_t CharacterAppearanceId = 0x2C8;          // unchanged (Player::UserId area)
    inline constexpr uintptr_t ClickDetectorMaxActivationDistance = 0x100; // unchanged (ClickDetector::MaxActivationDistance)
    inline constexpr uintptr_t ClockTime = 0x1B8;                      // unchanged (Lighting::ClockTime)
    inline constexpr uintptr_t CreatorId = 0x188;                      // unchanged (DataModel::CreatorId)
    inline constexpr uintptr_t DataModelDeleterPointer = 0x7A1D390;
    inline constexpr uintptr_t DataModelPrimitiveCount = 0x440;        // unchanged (DataModel::PrimitiveCount)
    inline constexpr uintptr_t DataModelToRenderView1 = 0x1D0;         // unchanged (DataModel::ToRenderView1)
    inline constexpr uintptr_t DataModelToRenderView2 = 0x8;           // unchanged (DataModel::ToRenderView2)
    inline constexpr uintptr_t DataModelToRenderView3 = 0x28;          // unchanged (DataModel::ToRenderView3)
    inline constexpr uintptr_t DecalTexture = 0x198;                   // unchanged (Textures::Decal_Texture)
    inline constexpr uintptr_t Deleter = 0x10;
    inline constexpr uintptr_t DeleterBack = 0x18;
    inline constexpr uintptr_t Dimensions = 0xA90;                     // updated (VisualEngine::Dimensions)
    inline constexpr uintptr_t DisplayName = 0x130;                    // unchanged (Player::DisplayName)
    inline constexpr uintptr_t EvaluateStateMachine = 0x1E4;           // updated (Humanoid::EvaluateStateMachine)
    inline constexpr uintptr_t FFlagList = 0x782d5f8;                  // unchanged (FFlags still version-390ba09e7e944154)
    inline constexpr uintptr_t FFlagToValueGetSet = 0x30;
    inline constexpr uintptr_t FOV = 0x160;                            // unchanged (Camera::FieldOfView)
    inline constexpr uintptr_t FogColor = 0xFC;                        // unchanged (Lighting::FogColor)
    inline constexpr uintptr_t FogEnd = 0x134;                         // unchanged (Lighting::FogEnd)
    inline constexpr uintptr_t FogStart = 0x138;                       // unchanged (Lighting::FogStart)
    inline constexpr uintptr_t ForceNewAFKDuration = 0x1B8;
    inline constexpr uintptr_t FramePositionOffsetX = 0x51C;           // unchanged (GuiObject::Position offset)
    inline constexpr uintptr_t FramePositionOffsetY = 0x524;
    inline constexpr uintptr_t FramePositionX = 0x518;                 // unchanged (GuiObject::Position)
    inline constexpr uintptr_t FramePositionY = 0x520;
    inline constexpr uintptr_t FrameRotation = 0x188;                  // unchanged (GuiObject::Rotation / GuiBase2D::AbsoluteRotation)
    inline constexpr uintptr_t FrameSizeOffsetX = 0x540;
    inline constexpr uintptr_t FrameSizeOffsetY = 0x544;
    inline constexpr uintptr_t FrameSizeX = 0x538;                     // unchanged (GuiObject::Size)
    inline constexpr uintptr_t FrameSizeY = 0x53C;
    inline constexpr uintptr_t FrameVisible = 0x5B5;                   // unchanged (GuiObject::Visible)
    inline constexpr uintptr_t GameId = 0x190;                         // unchanged (DataModel::GameId)
    inline constexpr uintptr_t GameLoaded = 0x5F8;                     // unchanged (DataModel::GameLoaded)
    inline constexpr uintptr_t Gravity = 0x210;                        // updated (World::Gravity)
    inline constexpr uintptr_t Health = 0x194;                         // unchanged (Humanoid::Health)
    inline constexpr uintptr_t HealthDisplayDistance = 0x198;          // unchanged (Humanoid::HealthDisplayDistance)
    inline constexpr uintptr_t HipHeight = 0x1A0;                      // unchanged (Humanoid::HipHeight)
    inline constexpr uintptr_t HumanoidDisplayName = 0xD0;             // unchanged (Humanoid::DisplayName)
    inline constexpr uintptr_t HumanoidState = 0x8A0;                  // updated (Humanoid::HumanoidState)
    inline constexpr uintptr_t HumanoidStateId = 0x20;                 // unchanged (Humanoid::HumanoidStateID)
    inline constexpr uintptr_t InputObject = 0x100;                    // unchanged (MouseService::InputObject)
    inline constexpr uintptr_t InsetMaxX = 0x100;
    inline constexpr uintptr_t InsetMaxY = 0x104;
    inline constexpr uintptr_t InsetMinX = 0xF8;
    inline constexpr uintptr_t InsetMinY = 0xFC;
    inline constexpr uintptr_t InstanceAttributePointer1 = 0x48;       // unchanged (Instance::AttributeContainer)
    inline constexpr uintptr_t InstanceAttributePointer2 = 0x18;       // unchanged (Instance::AttributeList)
    inline constexpr uintptr_t InstanceCapabilities = 0x208;
    inline constexpr uintptr_t JobEnd = 0xD0;                          // unchanged (TaskScheduler::JobEnd)
    inline constexpr uintptr_t JobId = 0x138;                          // unchanged (DataModel::JobId)
    inline constexpr uintptr_t JobStart = 0xC8;                        // unchanged (TaskScheduler::JobStart)
    inline constexpr uintptr_t Job_Name = 0x18;                        // unchanged (TaskScheduler::JobName)
    inline constexpr uintptr_t JobsPointer = 0x0;
    inline constexpr uintptr_t JumpPower = 0x1B0;                      // unchanged (Humanoid::JumpPower)
    inline constexpr uintptr_t LocalPlayer = 0x130;                    // unchanged (Player::LocalPlayer)
    inline constexpr uintptr_t LocalScriptBytecodePointer = 0x10;
    inline constexpr uintptr_t LocalScriptHash = 0x1B8;                // unchanged (LocalScript::Hash)
    inline constexpr uintptr_t MaterialType = 0x246;
    inline constexpr uintptr_t MaxHealth = 0x1B4;                      // unchanged (Humanoid::MaxHealth)
    inline constexpr uintptr_t MaxSlopeAngle = 0x1B8;                  // unchanged (Humanoid::MaxSlopeAngle)
    inline constexpr uintptr_t MeshPartColor3 = 0x194;                 // unchanged (BasePart::Color3)
    inline constexpr uintptr_t MeshPartTexture = 0x328;                // updated (MeshPart::Texture)
    inline constexpr uintptr_t ModelInstance = 0x398;                  // unchanged (Player::ModelInstance)
    inline constexpr uintptr_t ModuleScriptBytecodePointer = 0x10;
    inline constexpr uintptr_t ModuleScriptHash = 0x160;               // unchanged (ModuleScript::Hash)
    inline constexpr uintptr_t MoonTextureId = 0xE0;                   // unchanged (Sky::MoonTextureId)
    inline constexpr uintptr_t MousePosition = 0xEC;                   // unchanged (MouseService::MousePosition)
    inline constexpr uintptr_t MouseSensitivity = 0x7cb9ad0;           // updated (MouseService::SensitivityPointer)
    inline constexpr uintptr_t MoveDirection = 0x158;                  // unchanged (Humanoid::MoveDirection)
    inline constexpr uintptr_t NameDisplayDistance = 0x1BC;            // unchanged (Humanoid::NameDisplayDistance)
    inline constexpr uintptr_t NameSize = 0x10;
    inline constexpr uintptr_t OnDemandInstance = 0x40;
    inline constexpr uintptr_t OutdoorAmbient = 0x108;                 // unchanged (Lighting::OutdoorAmbient)
    inline constexpr uintptr_t Parent = 0x70;                          // unchanged (Instance::Parent)
    inline constexpr uintptr_t PartSize = 0x1B0;                       // unchanged (Primitive::Size)
    inline constexpr uintptr_t Ping = 0xCC;
    inline constexpr uintptr_t PlaceId = 0x198;                        // unchanged (DataModel::PlaceId)
    inline constexpr uintptr_t PlayerConfigurerPointer = 0x7bee8e8;    // updated (PlayerConfigurer::Pointer)
    inline constexpr uintptr_t PlayerMouse = 0x1168;                   // updated (Player::Mouse)
    inline constexpr uintptr_t Position = 0xE4;                        // unchanged (Primitive::Position)
    inline constexpr uintptr_t Primitive = 0x148;                      // unchanged (BasePart::Primitive)
    inline constexpr uintptr_t PrimitiveValidateValue = 0x6;           // unchanged (Primitive::Validate)
    inline constexpr uintptr_t PrimitivesPointer1 = 0x3E0;
    inline constexpr uintptr_t PrimitivesPointer2 = 0x240;
    inline constexpr uintptr_t ProximityPromptActionText = 0xC8;       // updated (ProximityPrompt::ActionText)
    inline constexpr uintptr_t ProximityPromptEnabled = 0x14E;         // updated (ProximityPrompt::Enabled)
    inline constexpr uintptr_t ProximityPromptGamepadKeyCode = 0x134;  // updated (ProximityPrompt::GamepadKeyCode)
    inline constexpr uintptr_t ProximityPromptHoldDuraction = 0x138;   // updated (ProximityPrompt::HoldDuration)
    inline constexpr uintptr_t ProximityPromptMaxActivationDistance = 0x140; // updated (ProximityPrompt::MaxActivationDistance)
    inline constexpr uintptr_t ProximityPromptMaxObjectText = 0xE8;    // updated (ProximityPrompt::ObjectText)
    inline constexpr uintptr_t ReadOnlyGravity = 0x9B8;                // updated (Workspace::ReadOnlyGravity)
    inline constexpr uintptr_t RenderJobToDataModel = 0x1C0;           // updated (RenderJob::RealDataModel)
    inline constexpr uintptr_t RenderJobToFakeDataModel = 0x38;        // unchanged (RenderJob::FakeDataModel)
    inline constexpr uintptr_t RenderJobToRenderView = 0x1D0;          // unchanged (RenderJob::RenderView)
    inline constexpr uintptr_t RequireBypass = 0x0;                    // unchanged (ScriptContext::RequireBypass)
    inline constexpr uintptr_t RigType = 0x1CC;                        // updated (Humanoid::RigType)
    inline constexpr uintptr_t RootPartR15 = 0x480;                    // updated (Humanoid::HumanoidRootPart)
    inline constexpr uintptr_t RootPartR6 = 0x480;                     // updated
    inline constexpr uintptr_t Rotation = 0xC8;
    inline constexpr uintptr_t RunContext = 0x148;
    inline constexpr uintptr_t Sandboxed = 0xC5;
    inline constexpr uintptr_t ScreenGuiEnabled = 0x4CC;               // unchanged (GuiObject::ScreenGui_Enabled)
    inline constexpr uintptr_t ScriptContext = 0x3F0;                  // unchanged (DataModel::ScriptContext)
    inline constexpr uintptr_t Sit = 0x1E9;                            // updated (Humanoid::Sit)
    inline constexpr uintptr_t SkyboxBk = 0x110;                       // unchanged (Sky::SkyboxBk)
    inline constexpr uintptr_t SkyboxDn = 0x140;                       // unchanged (Sky::SkyboxDn)
    inline constexpr uintptr_t SkyboxFt = 0x170;                       // unchanged (Sky::SkyboxFt)
    inline constexpr uintptr_t SkyboxLf = 0x1A0;                       // unchanged (Sky::SkyboxLf)
    inline constexpr uintptr_t SkyboxRt = 0x1D0;                       // unchanged (Sky::SkyboxRt)
    inline constexpr uintptr_t SkyboxUp = 0x200;                       // unchanged (Sky::SkyboxUp)
    inline constexpr uintptr_t SoundId = 0xE0;                         // unchanged (Sound::SoundId)
    inline constexpr uintptr_t StarCount = 0x260;                      // unchanged (Sky::StarCount)
    inline constexpr uintptr_t StringLength = 0x10;                    // unchanged (Misc::StringLength)
    inline constexpr uintptr_t SunTextureId = 0x230;                   // unchanged (Sky::SunTextureId)
    inline constexpr uintptr_t TagList = 0x0;
    inline constexpr uintptr_t TaskSchedulerMaxFPS = 0xB0;             // unchanged (TaskScheduler::MaxFPS)
    inline constexpr uintptr_t TaskSchedulerPointer = 0x7cf5400;       // updated (TaskScheduler::Pointer)
    inline constexpr uintptr_t Team = 0x2A0;                           // unchanged (Player::Team)
    inline constexpr uintptr_t TeamColor = 0xD0;                       // unchanged (Team::BrickColor)
    inline constexpr uintptr_t TextLabelText = 0xA60;
    inline constexpr uintptr_t TextLabelVisible = 0x5B5;               // unchanged (GuiObject::Visible)
    inline constexpr uintptr_t Tool_Grip_Position = 0x4BC;             // updated (Tool::Grip)
    inline constexpr uintptr_t Transparency = 0xF0;                    // unchanged (BasePart::Transparency)
    inline constexpr uintptr_t UserId = 0x2C8;                         // unchanged (Player::UserId)
    inline constexpr uintptr_t ValueGetSetToValue = 0xC0;
    inline constexpr uintptr_t Velocity = 0xF0;                        // unchanged (Primitive::AssemblyLinearVelocity)
    inline constexpr uintptr_t ViewportSize = 0x2E8;                   // unchanged (Camera::ViewportSize)
    inline constexpr uintptr_t VisualEngine = 0x10;                    // unchanged (RenderView::VisualEngine)
    inline constexpr uintptr_t VisualEnginePointer = 0x77c6670;        // updated (VisualEngine::Pointer)
    inline constexpr uintptr_t VisualEngineToDataModel1 = 0xA70;       // updated (VisualEngine::FakeDataModel)
    inline constexpr uintptr_t VisualEngineToDataModel2 = 0x1C0;
    inline constexpr uintptr_t WalkSpeed = 0x1DC;                      // updated (Humanoid::Walkspeed)
    inline constexpr uintptr_t WalkSpeedCheck = 0x3C4;                 // updated (Humanoid::WalkspeedCheck)
    inline constexpr uintptr_t Workspace = 0x178;                      // unchanged (DataModel::Workspace)
    inline constexpr uintptr_t WorkspaceToWorld = 0x408;               // updated (Workspace::World)
    inline constexpr uintptr_t viewmatrix = 0x130;                     // unchanged (VisualEngine::ViewMatrix)
}
